### ISSUE TITLE
Add Github Guidelines to README

### ISSUE THREAD

**Issue by sircharleswatson** [sircharleswatson/TaskHero#15]
customized version of this:
http://www.yegor256.com/2014/04/15/github-guidelines.html

**Comment by johnstonbl01** [comment]
I'll take this one. Think I can get it done by the end of the week.

**Comment by johnstonbl01** [comment]
A few questions about the pull request for this issue:

- "Don't expect anyone to help you. Your only source of help is the source code itself. If the code doesn't explain everything you need to know — it is a bug, which must be reported."  That seems a bit harsh. If it's an open source project, we want to encourage people to contribute by helping.
- I think it would be helpful to include additional information about expectations when submitting a bug request: i.e. what information is required?
- I also think it would be helpful to include information related to what's expected when volunteering to help with an issue
- "It's very common to receive a task that you may not be able to implement. Don't panic. This usually happens when you first join a project and don't yet have enough information. If this happens, don't try to figure out a problem or issue by yourself." Contributors (outside of the core contribution team) should be volunteering to help with issues, and not have them assigned IMO.

I still think some of the information in the [repo I linked earlier](https://github.com/johnstonbl01/fccTimeCoordinatorApp#contribution-guidelines) would be helpful (I borrowed heavily from the ESLint docs when putting that together).

**Comment by sircharleswatson** [comment]
Thanks Blake! I agree with most of this stuff. but I want to keep the spirit of the point but make it more open-source friendly.

Can you create a new issue to address these points? (also I think the docs you linked should be a separate issue from this.)  I'll merge this in for now and close this issue.

**Comment by sircharleswatson** [comment]
closed with #17
